# Basic config
baseURL = "https://gregpetrov.github.io/blog"
theme = "hugo-simple"
languageCode = "en"                # zh-Hans
title = "Greg Petrov's Blog"
copyright = "© 2024 Greg Petrov"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# https://github.com/gohugoio/hugo/issues/12152
capitalizeListTitles = false

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
# ignoreErrors = ["error-disable-taxonomy"]
[taxonomies]
tag = "tags"

[permalinks]
blog = "/:slugorfilename/"
tags = "/notes/:slug"

[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
startLevel = 2
endLevel = 3
[markup.highlight]
lineNos = true
lineNumbersInTable = false
noClasses = true
style = "catppuccin-mocha"

[params]
title = "Greg Petrov's Blog"
description = "Do not read it. There are more interesting things."
favicon = "images/favicon.png"
dateFormat = "2006-01-02"
hideMadeWithLine = false
hideRSSLink = false
[params.author]
name = "Greg Petrov"
email = "greg.petrov@donotcontact.me"

[[menu.main]]
name = "Home"
pageRef = "/"
weight = 10
[[menu.main]]
name = "Notes"
pageRef = "/notes"
weight = 20

[services.rss]
limit = 42

[outputs]
# Generate RSS for home only.
section = ["html"]
taxonomy = ["html"]
term = ["html"]
